source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  # Keep the native renderer ABI aligned with KUIKLY_VERSION in gradle.properties.
  pod 'OpenKuiklyIOSRender' , '~> 2.15.0'
  pod 'shared', :path => '../shared'

  pod 'SDWebImage'
end
