{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kuiklyklinechart/0.1.0-2.1.21/kuiklyklinechart-0.1.0-2.1.21.module",
    "group": "io.github.qingfeng19491001",
    "module": "kuiklyklinechart",
    "version": "0.1.0-2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "KuiklyKLineChart-release.aar",
          "url": "kuiklyklinechart-android-0.1.0-2.1.21.aar",
          "size": 771998,
          "sha512": "1f5d5594aa4b2b99d11a76cba59159cc3fa6356dd7dcadba2c9aceb7cec85c52197717cea604fa548352d90a754f0fa82d43b739fe6aac5f19101c971ecc6cf1",
          "sha256": "f4548fcf488c8c41bfda5cecff12e4ff3c3ad0fbc34b082fa5cf32a55b4d4cbc",
          "sha1": "a3b913738c3ec03a3a89c31f5abb2b5986178f34",
          "md5": "3de6230e96a13770c54df2fa527370dd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.tencent.kuikly-open",
          "module": "core-render-android",
          "version": {
            "requires": "2.15.0-2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core",
          "version": {
            "requires": "2.15.0-2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core-annotations",
          "version": {
            "requires": "2.15.0-2.1.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "KuiklyKLineChart-release.aar",
          "url": "kuiklyklinechart-android-0.1.0-2.1.21.aar",
          "size": 771998,
          "sha512": "1f5d5594aa4b2b99d11a76cba59159cc3fa6356dd7dcadba2c9aceb7cec85c52197717cea604fa548352d90a754f0fa82d43b739fe6aac5f19101c971ecc6cf1",
          "sha256": "f4548fcf488c8c41bfda5cecff12e4ff3c3ad0fbc34b082fa5cf32a55b4d4cbc",
          "sha1": "a3b913738c3ec03a3a89c31f5abb2b5986178f34",
          "md5": "3de6230e96a13770c54df2fa527370dd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "KuiklyKLineChart-android-0.1.0-2.1.21-sources.jar",
          "url": "kuiklyklinechart-android-0.1.0-2.1.21-sources.jar",
          "size": 114179,
          "sha512": "27d8bb7faa308141b3da3e5d7dae546a05ff20e0a940e71089f2f660c9f425f395d7cf43a6b2c299dd7661d2648ac175bf2572f122e0e02c7943466aaa5346b0",
          "sha256": "bc9bce318a699591a9dfff0526787097127832e94c84e8582aac81be3e46f6de",
          "sha1": "2d095ba6fa1a85ccb081cd3fa44fc2b48f3ffb37",
          "md5": "7eac43ba4074edb40d96f94b79d337fa"
        }
      ]
    }
  ]
}
