{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kuiklyklinechart/0.1.0-2.1.21/kuiklyklinechart-0.1.0-2.1.21.module",
    "group": "io.github.qingfeng19491001",
    "module": "kuiklyklinechart",
    "version": "0.1.0-2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core",
          "version": {
            "requires": "2.15.0-2.1.21"
          }
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core-annotations",
          "version": {
            "requires": "2.15.0-2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "KuiklyKLineChart-iosSimulatorArm64Main-0.1.0-2.1.21.klib",
          "url": "kuiklyklinechart-iossimulatorarm64-0.1.0-2.1.21.klib",
          "size": 866706,
          "sha512": "9f1c1236cca49ed09ce52e6699a14968d18e278847b37d6a87c63959ac6fe8b54001fe935cc93d7b878145bbbe193ec25c8311918962e248d160dceaf4d429ef",
          "sha256": "aa430d580b284292553e990917b0d8d18e140ab62daadefa5c30d75412b8ee54",
          "sha1": "ead25251510e7b4d92353957a9080f5f557e3464",
          "md5": "b0472fbad6a942bbfc75ac951218214d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "KuiklyKLineChart-iossimulatorarm64-0.1.0-2.1.21-sources.jar",
          "url": "kuiklyklinechart-iossimulatorarm64-0.1.0-2.1.21-sources.jar",
          "size": 113154,
          "sha512": "99692f63059d36fdeaeba11045cd0eaa15f80e6e3d94885a825d4de4eba0ce5fbcb2a3c3301ed2fe1688ddcf0bd1dcb83627376f1e4751dc213046a7febaeb3b",
          "sha256": "d04853e0d8a509227c2dff5a47261239ce44c78de2c29354abaf5bf1c6871593",
          "sha1": "2afc64a587fc39d2cbbdafb59ce38046db2f72db",
          "md5": "2181ca2cb497a9574b4b68274580be24"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core",
          "version": {
            "requires": "2.15.0-2.1.21"
          }
        },
        {
          "group": "com.tencent.kuikly-open",
          "module": "core-annotations",
          "version": {
            "requires": "2.15.0-2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "KuiklyKLineChart-iossimulatorarm64-0.1.0-2.1.21-metadata.jar",
          "url": "kuiklyklinechart-iossimulatorarm64-0.1.0-2.1.21-metadata.jar",
          "size": 3389,
          "sha512": "d83c951301fa890a59aafe08cf003b62c4d0edaf3077410e0594866cb7bdcdbfa26d1f6b36df69ce780038bb3ed73969bf2cfdd7ffb52893fc1357a7cccdbea6",
          "sha256": "276c7ac0d28799f62605954af5eae135d79bbc56d473e16c0280a2da908df787",
          "sha1": "60077c93ed05dba9d5d2a887394ecb1d22e3e285",
          "md5": "2e9d7f5aadbfd48fedc1578521e14271"
        }
      ]
    }
  ]
}
